export const VISUAL_CONTEXT_FIXTURES = {
  areaV0: {
    captureId: "cap_area_v0",
    page: { title: "Dashboard", url: "https://example.test/dashboard" },
    pins: [{
      box: { height: 80, width: 240, x: 16, y: 48 },
      comment: "Crop the chart",
      kind: "area",
      number: 1,
    }],
  },
  elementV0: {
    captureId: "cap_element_v0",
    page: {
      title: "Pricing",
      url: "https://example.test/pricing",
      viewport: { dpr: 2, height: 900, width: 1440 },
    },
    pins: [{
      anchor: { x: 90, y: 112 },
      box: { height: 40, width: 160, x: 24, y: 80 },
      comment: "Make the CTA bolder",
      id: "pin_cta",
      kind: "element",
      label: "button.cta",
      path: "main > section.card > button.cta",
      selector: "button.cta",
      text: "Get started",
    }],
  },
  iframeV0: {
    captureId: "cap_iframe_v0",
    page: { title: "Embed", url: "https://example.test/embed" },
    pins: [{
      comment: "Submit inside the frame",
      coords: { x: 12, y: 18 },
      frameId: 2,
      kind: "element",
      path: "html > body > iframe > html > body > button",
      selector: "button.submit",
    }],
  },
  invalidPinsObject: {
    captureId: "cap_invalid",
    page: { title: "Secret page", url: "https://example.test/secret" },
    pins: { comment: "UNIQUE_SECRET_PIN_COMMENT" },
  },
  legacyAliases: {
    captureId: "cap_legacy_aliases",
    page: { title: "Legacy", url: "https://example.test/legacy" },
    pins: [{
      comment: "Fix header",
      kind: "element",
      path: "header > h1",
      selector: "h1",
      text: "Welcome",
    }],
  },
  missingScreenshot: {
    captureId: "cap_missing_shot",
    page: { title: "No shot", url: "https://example.test/none" },
    pins: [{ comment: "Still useful", coords: { x: 4, y: 8 } }],
  },
  richV1: {
    captureId: "cap_rich_v1",
    page: { title: "Checkout", url: "https://example.test/checkout" },
    pins: [{
      comment: "Button is misaligned and the request fails",
      diagnosis: {
        acceptedAt: "2026-09-08T00:00:00.000Z",
        cause: "The button has line-height 1 while its siblings inherit 1.5.",
        confidence: "medium",
        fix: "button.pay { line-height: 1.5; }",
        properties: ["line-height"],
        version: 1,
      },
      evidence: {
        environment: { browser: "Chrome 140", language: "pt-BR", online: true, viewport: { height: 900, width: 1440 } },
        items: [{
          at: "2026-09-08T00:00:01.000Z",
          grade: "after_interaction",
          kind: "http",
          method: "POST",
          origin: "https://example.test",
          status: 500,
          url: "https://example.test/api/pay?token=[redacted]",
        }, {
          at: "2026-09-07T23:59:00.000Z",
          grade: "same_page",
          kind: "console_error",
          message: "Warning: each child should have a key",
          origin: "https://example.test",
        }],
        version: 1,
      },
      number: 1,
      pinId: "pin_pay",
      selector: "button.pay",
      snapshot: {
        fonts: [{ family: "Inter", weight: "600" }],
        icons: [{ kind: "class", name: "lucide-credit-card" }],
        nodeCount: 2,
        root: {
          attrs: { class: "pay" },
          children: [{ tag: "span", text: "Pay now" }],
          styles: { "line-height": "16px", display: "inline-flex" },
          tag: "button",
        },
        truncated: false,
        version: 1,
      },
      tag: "button",
    }, {
      comment: "Pending diagnosis stays private",
      diagnosis: {
        cause: "Guess without acceptance",
        confidence: "low",
        fix: "",
        properties: [],
        version: 1,
      },
      number: 2,
      pinId: "pin_private",
    }],
    reproduction: {
      startedAt: "2026-09-07T23:58:00.000Z",
      steps: [
        { at: "2026-09-07T23:58:00.000Z", kind: "navigate", url: "https://example.test/checkout" },
        {
          at: "2026-09-07T23:58:05.000Z",
          kind: "input",
          locator: { cssSelector: "input[name=email]" },
          thumbnail: "data:image/jpeg;base64,/9j/4AAQ",
          value: "user@example.test",
        },
        { at: "2026-09-07T23:58:07.000Z", kind: "click", locator: { cssSelector: "button.pay", innerText: "Pay now" } },
      ],
      version: 1,
    },
    schemaVersion: 1,
  },
  v1StableIds: {
    captureId: "cap_stable",
    page: { title: "Stable", url: "https://example.test/stable" },
    pins: [{
      comment: "Keep this id",
      number: 3,
      pinId: "pin_custom_abc",
    }],
    schemaVersion: 1,
    screenshot: { missing: false, url: "/tmp/stable.png" },
    viewport: { devicePixelRatio: 2, height: 800, scrollX: 0, scrollY: 40, width: 1280 },
  },
} as const;
