/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InstallDotps1RouteImport } from './routes/install[.]ps1'
import { Route as InstallDotshRouteImport } from './routes/install[.]sh'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as CIdRouteImport } from './routes/c/$id'
import { Route as PIdRouteImport } from './routes/p/$id'
import { Route as ShotsIdRouteImport } from './routes/shots/$id'
import { Route as VIdRouteImport } from './routes/v/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotps1Route = InstallDotps1RouteImport.update({
  id: '/install.ps1',
  path: '/install.ps1',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotshRoute = InstallDotshRouteImport.update({
  id: '/install.sh',
  path: '/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsIdRoute = ShotsIdRouteImport.update({
  id: '/shots/$id',
  path: '/shots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VIdRoute = VIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/shots/$id': typeof ShotsIdRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/shots/$id': typeof ShotsIdRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$id': typeof CIdRoute
  '/p/$id': typeof PIdRoute
  '/shots/$id': typeof ShotsIdRoute
  '/v/$id': typeof VIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/install.ps1'
    | '/install.sh'
    | '/pricing'
    | '/success'
    | '/api/$'
    | '/c/$id'
    | '/p/$id'
    | '/shots/$id'
    | '/v/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/install.ps1'
    | '/install.sh'
    | '/pricing'
    | '/success'
    | '/api/$'
    | '/c/$id'
    | '/p/$id'
    | '/shots/$id'
    | '/v/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/install.ps1'
    | '/install.sh'
    | '/pricing'
    | '/success'
    | '/api/$'
    | '/c/$id'
    | '/p/$id'
    | '/shots/$id'
    | '/v/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  InstallDotps1Route: typeof InstallDotps1Route
  InstallDotshRoute: typeof InstallDotshRoute
  PricingRoute: typeof PricingRoute
  SuccessRoute: typeof SuccessRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CIdRoute: typeof CIdRoute
  PIdRoute: typeof PIdRoute
  ShotsIdRoute: typeof ShotsIdRoute
  VIdRoute: typeof VIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.ps1': {
      id: '/install.ps1'
      path: '/install.ps1'
      fullPath: '/install.ps1'
      preLoaderRoute: typeof InstallDotps1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.sh': {
      id: '/install.sh'
      path: '/install.sh'
      fullPath: '/install.sh'
      preLoaderRoute: typeof InstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/$id': {
      id: '/shots/$id'
      path: '/shots/$id'
      fullPath: '/shots/$id'
      preLoaderRoute: typeof ShotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$id': {
      id: '/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof VIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  InstallDotps1Route: InstallDotps1Route,
  InstallDotshRoute: InstallDotshRoute,
  PricingRoute: PricingRoute,
  SuccessRoute: SuccessRoute,
  ApiSplatRoute: ApiSplatRoute,
  CIdRoute: CIdRoute,
  PIdRoute: PIdRoute,
  ShotsIdRoute: ShotsIdRoute,
  VIdRoute: VIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
